In [2]:
#create a vector from 0 to 20 and change the sign of the nos from 9 to 15
import numpy as np
v=np.arange(21)
v[9:16]=-v[9:16]
print(v)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [4]:
#wpp a numpy program to compute all sum of elements,sum of each coloums row of given array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
total_sum=np.sum(arr)
print(total_sum)
csum=np.sum(arr,axis=0)
print(csum)
rsum=np.sum(arr,axis=1)
print(rsum)

45
[12 15 18]
[ 6 15 24]


In [8]:
#write a numpy program to save a given array to a file and load it
arrrr=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt('myarray.txt',arr,fmt='%d')
la=np.loadtxt('myarray.txt',dtype=int)
print(la)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#create a 4X4 matrix and fill it with random value create a new array from the set array by swapiing first and last row
arr3=np.random.rand(4,4)
print('OG array:')
print(arr3)
narr3=arr3.copy()
narr3[[0,-1]]=narr3[[-1,0]]
print('New array:')
print(narr3)

OG array:
[[0.64169458 0.93394475 0.00241733 0.07116644]
 [0.29278657 0.0578644  0.44146889 0.15413939]
 [0.27161967 0.64711499 0.2738202  0.49553939]
 [0.93915121 0.34255483 0.04781682 0.70080654]]
New array:
[[0.93915121 0.34255483 0.04781682 0.70080654]
 [0.29278657 0.0578644  0.44146889 0.15413939]
 [0.27161967 0.64711499 0.2738202  0.49553939]
 [0.64169458 0.93394475 0.00241733 0.07116644]]


In [10]:
#array multiplication of same size by elements to elements
a7=np.array([[1,2,3],[4,5,6]])
print(a7)
a8=np.array([[7,8,9],[10,11,12]])
print(a8)
mularr=a7*a8
print(mularr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 7 16 27]
 [40 55 72]]
