In [9]:
import numpy as np
A=np.array([1,2,3])
print(A.shape)

(3,)


In [24]:
B=np.array([[1, 2, 3],[2, 4, 6]])
print(B)
print(B.shape)
C=B.reshape(3,2)
print(C)

[[1 2 3]
 [2 4 6]]
(2, 3)
[[1 2]
 [3 2]
 [4 6]]


In [29]:
X=np.arange(1,24,2,dtype=float)
print(X)


[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23.]
