In [8]:
import numpy as np
A=np.array([12,32,12,32,45,12])
B=np.array([12,31,11,37,47,10])
print(A,B)
print(np.greater(A, B))
print(np.less(A, B))
print(np.greater_equal(A,B))
print(np.less_equal(A,B))
print(np.equal(A,B))



[12 32 12 32 45 12] [12 31 11 37 47 10]
[False  True  True False False  True]
[False False False  True  True False]
[ True  True  True False False  True]
[ True False False  True  True False]
[ True False False False False False]


In [10]:
X=np.arange(50,90,2)
print(X)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


In [12]:
I=np.identity(4,dtype=int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
D=np.diag([1,2,3,4,5])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
