In [1]:
import numpy as np
r1=int(input("Enter rows :"))
c1=int(input("Enter coloumns :"))
a=list(map(int,input('Enter the first array').split()))
mat=np.array(a).reshape(r1,c1)
b=list(map(int,input('Enter the second array').split()))
mat2=np.array(b).reshape(r1,c1)

Enter rows :2
Enter coloumns :2
Enter the first array1 2 3 4 
Enter the second array5 6 7 8


In [5]:
print(mat)
print(mat2)
print('dot product is : ')
m3=np.dot(mat,mat2)
m3

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
dot product is : 


array([[19, 22],
       [43, 50]])

In [6]:
print('Transpose is :')
m4=np.transpose(mat)
m5=np.transpose(mat2)
print(m4)
print(m5)

Transpose is :
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [7]:
print('Determenant :')
m6=np.linalg.det(mat)
print(m6)
m7=np.linalg.det(mat2)
print(m7)

Determenant :
-2.0000000000000004
-1.999999999999999


In [12]:
print("inverse of the matrix is: ")
m8=np.linalg.inv(mat)
print(m8)
m9=np.linalg.inv(mat2)
print(m9)

inverse of the matrix is: 
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]


In [13]:
print('Trace')
print(mat.trace())
print(mat2.trace())

Trace
5
13


In [15]:
print('rank')
r1=np.linalg.matrix_rank(mat)
r2=np.linalg.matrix_rank(mat2)
print(r1)
print(r2)

rank
2
2


In [16]:
print("eigen Values and Eigen Vectors")
eigenvalues, eigenvectors = np.linalg.eig(mat)
eigenvalues1, eigenvectors1 = np.linalg.eig(mat2)
print(eigenvalues, eigenvectors)
print(eigenvalues1, eigenvectors1)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-0.15206735 13.15206735] [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]
