In [8]:
import numpy as np
m1=np.array([[1,2],[3,4]])
print(m1)
m2=np.array([[5,6],[7,8]])
print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
#mul
m3=np.dot(m1,m2)
m3

array([[19, 22],
       [43, 50]])

In [11]:
#transpose
m4=np.transpose(m1)
m4

array([[1, 3],
       [2, 4]])

In [12]:
#inverse
m5=np.linalg.inv(m2)
m5

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [14]:
#determinant
m6=np.linalg.det(m1)
m6

-2.0000000000000004

In [16]:
#flatten
x=m1.flatten()
x

array([1, 2, 3, 4])

In [23]:
#read matrix from the user
matrix=[]
for i in range(2):
    row=[]
    for j in range(2):
        a=int(input('Enter the value :'))
        row.append(a)
    matrix.append(row)
    
print(matrix)

Enter the value :1
Enter the value :2
Enter the value :3
Enter the value :4
[[1, 2], [3, 4]]


In [26]:
#read rows and coloums
matrix1=[]
r=int(input('Enter the rows: '))
c=int(input("Enter the column: "))
for i in range(r):
    row=[]
    for j in range(c):
        a=int(input('Enter the value :'))
        row.append(a)
    matrix1.append(row)
    
print(matrix)


Enter the rows: 2
Enter the column: 2
Enter the value :1
Enter the value :2
Enter the value :3
Enter the value :4
[[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [1, 2], [3, 4]]
/n


In [30]:
#
r1=int(input("Enter rows :"))
c1=int(input("Enter coloumns :"))
a=list(map(int,input().split()))
mat=np.array(a).reshape(r1,c1)
mat

Enter rows :2
Enter coloumns :2
1 2 3 4 


array([[1, 2],
       [3, 4]])